name: Build and Deploy containerized app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: pythonflaskacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: pythonflaskacr.azurecr.io/flask-app:${{ github.sha }}
        cache-from: type=registry,ref=pythonflaskacr.azurecr.io/flask-app:latest
        cache-to: type=inline
        
    - name: Tag as latest
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: pythonflaskacr.azurecr.io/flask-app:latest
        cache-from: type=registry,ref=pythonflaskacr.azurecr.io/flask-app:${{ github.sha }}
        cache-to: type=inline

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: pythonflaskcont
        images: pythonflaskacr.azurecr.io/flask-app:${{ github.sha }}
        resource-group-name: pythonflaskcont_group
